# Site settings
title: "Last Minute: Politics"
description: "If we’re living at the end of history, these are the last minute politics."
podcast-description: "If we’re living at the end of history, these are the last minute politics."
url:  "https://jekyll-podcaster.netlify.app/" # Actual base url of the website
baseurl: ""                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Draggor"
  email: "draggor@gmail.com"
  url: "https://draggor.me"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll, politics, furry]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: lastminutepol
  card: summary
logo: /assets/img/Podcast_Cover.jpg
social:
  name: "Last Minute: Politics"
  links:
    - https://www.patreon.com/LastMinutePolitics
    - https://twitter.com/lastminutepol
    - https://open.spotify.com/show/18rMdpfy0mZxEpmyPyjzGO
    - https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkLnBvZGJlYW4uY29tL2xhc3RtaW51dGVwb2xpdGljcy9mZWVkLnhtbA
    - https://podcasts.apple.com/us/podcast/last-minute-politics/id1541888677
    - https://tunein.com/podcasts/News--Politics-Podcasts/Last-Minute-Politics-p1385646/
    - https://lastminutepolitics.podbean.com/
    - https://www.youtube.com/channel/UCjCsbAHwJUaRRVLdOaEnWxA
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: "Last Minute: Politics"
podcast_author: "Xanni, Pepper, and Draggor"
podcast_email: lastminutepoliticspodcast@gmail.com
podcast_subtitle: "Starring Xanni, Pepper, and Draggor"
podcast_summary: "If we’re living at the end of history, these are the last minute politics."
podcast_description: "If we’re living at the end of history, these are the last minute politics."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2020-11-24" #Launch date of your podcast
podcast_copyright: "&#xA9;Xanni, Pepper, Draggor"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.jpg"
